# Copyright 2016-2019 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

os: linux
arch: x86

compiler: vxworks-clang 
env: TOOLSET=clang COMPILER=vxworks-clang CXXSTD=17

before_install: 
        - pushd $TRAVIS_BUILD_DIR/..
        - wget https://labs.windriver.com/downloads/wrsdk-vxworks7-qemu-1.3.tar.bz2
        - tar xf wrsdk-vxworks7-qemu-1.3.tar.bz2
        - popd

before_script:
        - pushd $TRAVIS_BUILD_DIR/..
        - 'echo "The shell is **$0**"'
        - 'echo "The shell is **$SHELL**"'
        - 'ps -p "$$"'
        - 'cat /home/travis/build.sh' 
        - source wrsdk-vxworks7-qemu/toolkit/wind_sdk_env.linux
        - |-
           echo "The Path is **${PATH}**"
        - popd
        - rm project-config.jam
        - |-
           echo "import option  ;" >> ./project-config.jam
           echo "import feature ;" >> ./project-config.jam
           echo "import os ;     " >> ./project-config.jam
           echo "feature.feature cross-compile : vxworks : optional composite propagated ; " >> ./project-config.jam
           echo "feature.compose <cross-compile>vxworks : <threadapi>pthread <binary-format>elf <abi>sysv <threading>multi <target-os>vxworks ; " >> ./project-config.jam
           echo "feature.feature static-only : on : optional composite propagated ; " >> ./project-config.jam
           echo "feature.compose <static-only>on : <link>static ; " >> ./project-config.jam
           echo "using clang-vxworks : : $CXX : <cflags>$CFLAGS <cxxflags>$CXXFLAGS <compileflags>$CPPFLAGS <linkflags>$LDFLAGS <archiver>$AR <linker-type>vxworks <archiver>$AR <linker>$LD ;" >> ./project-config.jam
           echo "project : requirements  <static-only>on,<link>shared:<build>no <cross-compile>vxworks <exception-handling>off:<build>no ; " >> ./project-config.jamaddons:

        
apt:          
    packages: qemu-system-x86

install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/system
  - python tools/boostdep/depinst/depinst.py system
  - ./bootstrap.sh
  - ./b2 headers

script:
  - |-
       echo "using $TOOLSET : : $COMPILER ;" > ~/user-config.jam
  - ./b2 -j3 libs/system/test toolset=$TOOLSET cxxstd=$CXXSTD variant=debug,release ${UBSAN:+cxxflags=-fsanitize=undefined cxxflags=-fno-sanitize-recover=undefined linkflags=-fsanitize=undefined define=UBSAN=1 debug-symbols=on} ${LINKFLAGS:+linkflags=$LINKFLAGS}

notifications:
  email:
    on_success: always
