# Copyright 2016-2019 Peter Dimov
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

language: cpp

sudo: false

os: linux
compiler: clang 
addons:
    apt:
        packages: 
            - qemu-system-x86 
            - g++-multilib libncurses5:i386 libc6:i386 libgcc1:i386 gcc-4.8-base:i386 
            - libstdc++5:i386 libstdc++6:i386 libxtst6 libgtk2.0-0:i386 libxtst6:i386

cache:
    directories:
     - /home/travis/build/sdk


env: TOOLSET=clang-vxworks CXXSTD=17  

before_install: 
        - pushd /home/travis/build/sdk
        - if [ ! -d "wrsdk-vxworks7-qemu" ] ; then wget https://labs.windriver.com/downloads/wrsdk-vxworks7-qemu-1.3.tar.bz2 ; tar xf wrsdk-vxworks7-qemu-1.3.tar.bz2 ; fi
        - popd

before_script:
        - pushd /home/travis/build/sdk
        - source wrsdk-vxworks7-qemu/toolkit/wind_sdk_env.linux
        - export AR=x86-wrs-vxworks-ar
        - export LD=x86-wrs-vxworks-ld
        - export PKG_SRC_BUILD_DIR=`realpath $TRAVIS_BUILD_DIR/../boost-root`
        - export LAYER_SRC_PATH=boost-root
        - 'export BOOST_ARGS ="  --prefix=$WIND_SDK_INCLUDE/usr --libdir=$WIND_SDK_INCLUDE/usr/lib/common --includedir=$WIND_SDK_INCLUDE/usr/h/public "'
        - popd 
        - rm ./project-config.jam
        - |-
           echo "import option  ;" >> ./project-config.jam
           echo "import feature ;" >> ./project-config.jam
           echo "import os ;     " >> ./project-config.jam
           echo "feature.feature cross-compile : vxworks : optional composite propagated ; " >> ./project-config.jam
           echo "feature.compose <cross-compile>vxworks : <threadapi>pthread <binary-format>elf <abi>sysv <threading>multi <target-os>vxworks ; " >> ./project-config.jam
           echo "feature.feature static-only : on : optional composite propagated ; " >> ./project-config.jam
           echo "feature.compose <static-only>on : <link>static ; " >> ./project-config.jam
           echo "using clang-vxworks : : x86-wrs-vxworks-cxx : <archiver>x86-wrs-vxworks-ar <linker-type>vxworks <linker>x86-wrs-vxworks-ld ;" >> ./project-config.jam
           echo "project : requirements  <static-only>on,<link>shared:<build>no <cross-compile>vxworks <exception-handling>off:<build>no ; " >> ./project-config.jam
        - cat ./project-config.jam 
        - mkfifo /tmp/guest.in /tmp/guest.out
        


install:
  - BOOST_BRANCH=develop && [ "$TRAVIS_BRANCH" == "master" ] && BOOST_BRANCH=master || true
  - cd ..
  - git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
  - cd boost-root
  - git submodule update --init tools/boostdep
  - cp -r $TRAVIS_BUILD_DIR/* libs/system
  - python tools/boostdep/depinst/depinst.py system
  - ./bootstrap.sh
  - ./b2 headers

script:
  - ./b2 -j3 libs/system/test toolset=$TOOLSET cxxstd=$CXXSTD variant=debug,release testing.execute=off $BOOST_ARGS

#notifications:
#  email:
#    on_success: always
